"""
Material Requisition Service
Business logic for managing material requisitions
"""
from typing import List, Optional
from app.database import get_db
from app.schemas.material_requisition import (
    MaterialRequisitionCreate,
    MaterialRequisitionUpdate,
    MaterialRequisitionResponse,
    MaterialRequisitionSummary
)


class MaterialRequisitionService:
    """Service for managing material requisitions"""
    
    @staticmethod
    async def create_requisition(
        data: MaterialRequisitionCreate, 
        created_by: Optional[str] = None
    ) -> MaterialRequisitionResponse:
        """
        Create a new material requisition
        
        Args:
            data: Requisition data including items
            created_by: User ID of the creator (optional)
            
        Returns:
            Complete requisition with auto-generated requisition number
        """
        db = get_db()
        
        # Prepare requisition data (excluding items)
        req_data = data.model_dump(exclude={'items'}, mode="json")
        if created_by:
            req_data['created_by'] = created_by
        req_data['status'] = 'Pending'
        
        # Insert requisition (requisition_number auto-generated by trigger)
        result = db.table('material_requisitions').insert(req_data).execute()
        
        if not result.data:
            raise Exception("Failed to create material requisition")
        
        requisition = result.data[0]
        requisition_id = requisition['id']
        
        # Insert items
        items_data = [
            {**item.model_dump(mode="json"), 'requisition_id': requisition_id}
            for item in data.items
        ]
        
        items_result = db.table('material_requisition_items').insert(items_data).execute()
        
        if not items_result.data:
            # Rollback requisition if items fail
            db.table('material_requisitions').delete().eq('id', requisition_id).execute()
            raise Exception("Failed to create requisition items")
        
        # Get complete requisition
        requisition_response = await MaterialRequisitionService.get_requisition(requisition_id)
        
        # Create notification
        try:
            from app.services.notification_service import notification_service
            await notification_service.create_material_request_notification(requisition_response)
        except Exception as e:
            print(f"Warning: Failed to create notification for requisition {requisition_id}: {e}")
            
        return requisition_response
    
    @staticmethod
    async def get_requisition(requisition_id: str) -> MaterialRequisitionResponse:
        """
        Get a material requisition by ID
        
        Args:
            requisition_id: UUID of the requisition
            
        Returns:
            Complete requisition with items
        """
        db = get_db()
        
        # Get requisition
        req_result = db.table('material_requisitions').select('*').eq('id', requisition_id).single().execute()
        
        if not req_result.data:
            raise Exception(f"Requisition {requisition_id} not found")
        
        # Get items
        items_result = (
            db.table('material_requisition_items')
            .select('*')
            .eq('requisition_id', requisition_id)
            .order('created_at')
            .execute()
        )
        
        requisition = req_result.data
        requisition['items'] = items_result.data or []
        
        return MaterialRequisitionResponse(**requisition)
    
    @staticmethod
    async def get_requisition_by_number(requisition_number: str) -> MaterialRequisitionResponse:
        """
        Get a material requisition by requisition number
        
        Args:
            requisition_number: Requisition number (e.g., MR-2026-0001)
            
        Returns:
            Complete requisition with items
        """
        db = get_db()
        
        # Get requisition by number
        req_result = (
            db.table('material_requisitions')
            .select('*')
            .eq('requisition_number', requisition_number)
            .single()
            .execute()
        )
        
        if not req_result.data:
            raise Exception(f"Requisition {requisition_number} not found")
        
        return await MaterialRequisitionService.get_requisition(req_result.data['id'])
    
    @staticmethod
    async def list_requisitions(
        limit: int = 50,
        offset: int = 0,
        status: Optional[str] = None,
        department: Optional[str] = None
    ) -> List[MaterialRequisitionSummary]:
        """
        List material requisitions with filters
        
        Args:
            limit: Maximum number of results
            offset: Offset for pagination
            status: Filter by status
            department: Filter by department
            
        Returns:
            List of requisition summaries
        """
        db = get_db()
        
        query = (
            db.table('vw_material_requisitions_summary')
            .select('*')
            .order('created_at', desc=True)
            .limit(limit)
            .range(offset, offset + limit - 1)
        )
        
        if status:
            query = query.eq('status', status)
        
        if department:
            query = query.eq('department', department)
        
        result = query.execute()
        
        return [MaterialRequisitionSummary(**req) for req in result.data]
    
    @staticmethod
    async def update_requisition(
        requisition_id: str,
        data: MaterialRequisitionUpdate
    ) -> MaterialRequisitionResponse:
        """
        Update a material requisition
        
        Args:
            requisition_id: UUID of the requisition
            data: Update data
            
        Returns:
            Updated requisition
        """
        db = get_db()
        
        update_data = {
            k: v
            for k, v in data.model_dump(exclude_unset=True, mode="json").items()
            if v is not None
        }
        
        if not update_data:
            return await MaterialRequisitionService.get_requisition(requisition_id)
        
        result = db.table('material_requisitions').update(update_data).eq('id', requisition_id).execute()
        
        if not result.data:
            raise Exception(f"Requisition {requisition_id} not found")
        
        return await MaterialRequisitionService.get_requisition(requisition_id)
    
    @staticmethod
    async def delete_requisition(requisition_id: str) -> dict:
        """
        Delete a material requisition (soft delete by setting status to Cancelled)
        
        Args:
            requisition_id: UUID of the requisition
            
        Returns:
            Success message
        """
        db = get_db()
        
        result = (
            db.table('material_requisitions')
            .update({'status': 'Cancelled'})
            .eq('id', requisition_id)
            .execute()
        )
        
        if not result.data:
            raise Exception(f"Requisition {requisition_id} not found")
        
        return {"message": "Requisition cancelled successfully"}


# Create singleton instance
material_requisition_service = MaterialRequisitionService()
